### ISSUE TITLE
Permissions to run

### ISSUE THREAD

**Issue by josephernest** [alcover/runc#1]
Congrats for this great project!

What do you recommend to use it?

* put `lacy` in a `myscript/` directory which is in your `PATH`? (then I need to `chmod +x lacy`, is that right?)

* or put it anywhere and do an alias in `.bashrc` to be able to use it from anywhere?

**Comment by alcover** [comment]
Thanks !

Yes, all those ways are correct.

That is what the **install.sh** script does : 
- create a /home/you/bin if absent
- add bin/ to PATH
- update .bashrc
- hardlink lacy to bin
- chmod it

Please tell me if the script works for you.
Maybe this script should be advertized in the README ?

**Comment by josephernest** [comment]
Good idea!
Not sure if `/home/user1/bin` or `/home/user1/.bin` is a standard practice to store personal scripts, or if there's a dedicated directory for this (/usr/bin/? sbin? etc.). Would be cool to ask someone wiser than me to know the most usual usages about this :)

**Comment by alcover** [comment]
I took the liberty to re-open your thread.

Yes ~/bin is common practice.  
You can see it in .profile :  
```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
```
